import {
  BadgePercent,
  Bell,
  CreditCard,
  Crown,
  Gift,
  Heart,
  LogOut,
  MapPinned,
  Package,
  Sparkles,
  UserCircle2,
} from 'lucide-react';

export const accountMenuItems = [
  { label: 'My Profile', to: '/account/profile', icon: UserCircle2 },
  { label: 'Flipkart Plus Zone', to: '/account/plus', icon: Crown },
  { label: 'Orders', to: '/account/orders', icon: Package },
  { label: 'Wishlist', to: '/account/wishlist', icon: Heart },
  { label: 'Rewards', to: '/account/rewards', icon: Sparkles },
  { label: 'Gift Cards', to: '/account/gift-cards', icon: Gift },
  { label: 'Coupons', to: '/account/coupons', icon: BadgePercent },
  { label: 'Saved Cards', to: '/account/cards', icon: CreditCard },
  { label: 'Saved Addresses', to: '/account/addresses', icon: MapPinned },
  { label: 'Notifications', to: '/account/notifications', icon: Bell },
  { label: 'Logout', to: '#logout', icon: LogOut, isLogout: true },
];

export const accountPageCopy = {
  '/account/profile': {
    title: 'My Profile',
    description: 'Manage your personal information, contact details, and account preferences.',
    heading: 'Your profile is set up.',
    body: 'Your name, email, phone number, and profile photo can be managed here. Keep your details up to date to get the best shopping experience.',
    features: ['Edit name & display photo', 'Change email or mobile number', 'Update gender & birthday', 'Manage login security'],
  },
  '/account/plus': {
    title: 'Flipkart Plus Zone',
    description: 'Unlock exclusive benefits, free delivery, and SuperCoins with Flipkart Plus membership.',
    heading: 'Upgrade to Flipkart Plus.',
    body: 'Flipkart Plus members enjoy free and fast delivery, exclusive early access to sales, and SuperCoins on every purchase. Join millions of smart shoppers.',
    features: ['Free & priority delivery on eligible orders', 'Earn 2× SuperCoins on every order', 'Early access to Big Billion Days & sales', 'Exclusive member-only offers'],
  },
  '/account/orders': {
    title: 'Orders',
    description: 'Track your current orders and view your complete purchase history.',
    heading: 'All your orders in one place.',
    body: 'View real-time shipment tracking, download invoices, request returns or exchanges, and browse your full order history across all categories.',
    features: ['Live shipment tracking', 'Download GST invoices', 'Easy return & exchange requests', 'Order history & reorder'],
  },
  '/account/wishlist': {
    title: 'Wishlist',
    description: 'Products you saved for later and price-drop alerts.',
    heading: 'Save products for later.',
    body: 'Add products to your wishlist to save them for later. Get notified when prices drop and share your wishlist with friends and family.',
    features: ['Save items you love', 'Get price drop alerts', 'Move items directly to cart', 'Share wishlist with others'],
  },
  '/account/rewards': {
    title: 'Rewards',
    description: 'Your SuperCoins balance, earned rewards, and available offers.',
    heading: 'Earn & redeem SuperCoins.',
    body: 'SuperCoins are earned on every Flipkart purchase and can be redeemed for discounts, free delivery, and partner brand benefits like Hotstar and more.',
    features: ['Earn SuperCoins on every order', 'Redeem on future purchases', 'Use with Hotstar, Cleartrip & more', 'Bonus coins on Plus membership'],
  },
  '/account/gift-cards': {
    title: 'Gift Cards',
    description: 'Check your gift card balance, redeem codes, and buy new gift cards.',
    heading: 'Give the gift of choice.',
    body: 'Flipkart Gift Cards are the perfect gift — available in any denomination, redeemable across millions of products, and valid for 1 year from purchase date.',
    features: ['Check gift card balance', 'Redeem a gift card code', 'Buy gift cards for any occasion', 'Valid on all product categories'],
  },
  '/account/coupons': {
    title: 'Coupons',
    description: 'Your saved coupon codes and available discount offers.',
    heading: 'Your coupons & discounts.',
    body: 'Coupons are automatically applied at checkout for eligible orders. Save coupons from promotional emails or claim them from flash sale events.',
    features: ['Auto-applied at checkout', 'Category & brand-specific coupons', 'Bank offer coupons', 'Claim event coupons'],
  },
  '/account/cards': {
    title: 'Saved Cards',
    description: 'Securely saved debit and credit cards for faster checkout.',
    heading: 'Faster checkout every time.',
    body: 'Save your debit and credit cards securely for one-tap checkout. All card data is encrypted and stored with PCI-DSS compliant payment partners.',
    features: ['Save Visa, Mastercard & RuPay cards', 'One-tap checkout on all devices', 'Bank offers applied automatically', 'Remove or update cards anytime'],
  },
  '/account/addresses': {
    title: 'Saved Addresses',
    description: 'Manage your delivery addresses for fast and accurate shipping.',
    heading: 'Deliver anywhere you want.',
    body: 'Add and manage multiple delivery addresses — home, office, or anywhere else. Set a default address for even faster checkout every time you shop.',
    features: ['Add multiple delivery addresses', 'Set a default address', 'Edit or remove addresses anytime', 'Used across all your orders'],
  },
  '/account/notifications': {
    title: 'Notifications',
    description: 'Control your order alerts, offers, and account notification preferences.',
    heading: 'Stay in the loop.',
    body: 'Get real-time updates on your orders, exclusive sale alerts, price-drop notifications on wishlisted products, and important account security alerts.',
    features: ['Order & delivery updates', 'Price drop alerts on saved items', 'Exclusive sale & offer alerts', 'Account security notifications'],
  },
};
